FROM node:lts-slim

WORKDIR /app

ENV NODE_ENV=development

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Expose port 5173 (Vite's default port)
EXPOSE 5173
